### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-intermedia-Celiamf#1]
Muy buen trabajo @Celiamf!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 250 / 347
- [x] CARPETAS > CSS: La ruta del fichero CSS debe empezar por `./styles/` o `./css/`.
- [x] CARPETAS > IMG: Los ficheros de imágenes deben empezar por `./images/` o `./img/`.
- [x] HTML > LINK: El fichero de fuentes debe estar antes que nuestro fichero de estilos para que ningún fichero de estilos externo sobre escriba los nuestros.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: Los enlaces tienen que tener el atributo `title`.
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos. `.menu { flex-direction: row }`
- [x] CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px.
- [x] CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px.
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.
- [x] CSS > FLEX: El texto Creando diversidad digital debe estar centrado horizontal y verticalmente, lo mejor es hacerlo con flex.
- [x] CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha .

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te encaja dímelo cuanto antes por favor.

> Para corregir el ejercicio buscamos determinadas palabras en el código para identificar las secciones. Por ejemplo buscamos **Anonymous** para buscar el hero. Si has escrito mal alguna palabra en el código es posible que te aparezcan aquí falsos errores.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by Celiamf** [comment]
¡Gracias por la revisión!

-  En el error _CARPETAS > CSS: La ruta del fichero CSS debe empezar por ./styles/ o ./css/._, ¿es posible que sea porque el nombre de la carpeta Styles lo he escrito con mayúscula inicial? ¿Es un error hacerlo así, o más bien resulta poco recomendable? Se me ocurre que sea eso porque el ._/ sí_ lo he  puesto. Sé que hay que evitarlas, pero se me escapan mayúsculas iniciales por todas partes (deformación profesional).

- _CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px._ El tamaño de la fuente se lo he puesto al contenedor de este h1 en las dos medidas. ¿Es incorrecto o también valdría?

**Comment by migueldelmazo** [comment]
Hola @Celiamf,

- Respecto a En el error CARPETAS > CSS: La ruta del fichero CSS debe empezar por ./styles/ o ./css/... esto no es obligatorio, es recomendable. Solemos poner los nombres de ficheros siempre en minúsculas, sin espacios, sin acentos... ya que en algunos ordenadores o servidores dan problemas. Y decidamos el nombre que decidamos debemos poner el nombre exacto en el código, ya que por ejemplo en linux el fichero Main.css es diferente del fichero main.css.

- Respecto a CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px... fallo mío, disculpa. Márcalo como solucionado y punto.

**Comment by Celiamf** [comment]
¡Gracias Miguel!
